### ISSUE TITLE
Parsing JSON data

### ISSUE THREAD

**Issue by joker1** [dblock/oshi#179]
The problem: oshi supports writing SystemInfo as JSON data but does not support reading it back.

Solution: Add JSON reading/parsing support to SystemInfo. This would be useful, for example, in scenarios where SystemInfo is written to database (such as MongoDB which supports JSON natively) and needs to be read back.

**Comment by dbwiddis** [comment]
I'm not understanding the use case for this.  Most of the information in oshi is intended to be read real-time from the operating system rather than populated from external sources.   When/how would I be writing external information to oshi?

**Comment by joker1** [comment]
I have been on vacation and therefore not been able to answer your question. The use case for this: we have a cluster of N nodes and these nodes have to be able to exchange os/hw information so it can be viewed in a web user-interface. This information needs to be available for every node and preferable even when (some of the) nodes are offline. Therefore I would like to be able to write it to database and use that cached information when a node is offline and real-time information can not be retrieved.

**Comment by dbwiddis** [comment]
Well, I understand the use case now, but I'm not sure that's something I want to put into oshi, at least at the lower level.

For some of the classes/interfaces that have setter methods, it's reasonable to think that using a `setJSON()` method could populate some of the values.  However, many values are simply not stored variables, and are always retrieved when the method is called.  GlobalMemory is a good example; while total memory is going to stay the same, the available memory, and total/used swap may change every time the method is called.

I think there's certainly a case to be made for a higher level module that has persistent attributes such as you describe, but it'd be a new layer on top of the existing core functionality, designed to retrieve data rather than store it.  Which is something I think is better left to end users to decide how (and what) they want to persist.

**Comment by joker1** [comment]
Thanks for the response, after reading it I agree that this is probably better handled separately.

**Comment by dbwiddis** [comment]
Now if you wanted to contribute such a higher level model, like oshi-db, you could ingest the json from oshi, translate to jackson and store in mongoDB... :)
