### ISSUE TITLE
systemSerialNumber is unknown

### ISSUE THREAD

**Issue by damarasekara** [dblock/oshi#237]
It returns systemSerialNumber as unknown when running on linux? However when it is run with root permission, it returns a value.

Any input for this is appreciated.

**Comment by dbwiddis** [comment]
It seems the Linux kernel developers valued privacy and require root permissions to read the system serial number.  One must install a separate software package (that runs as root) in order to access this information as non-root.  

As documented in the [Javadoc](http://dblock.github.io/oshi/apidocs/oshi/hardware/CentralProcessor.html#getSystemSerialNumber--), getting the serial number on Linux requires either root permissions (to use the dmidecode command) or installation of the (deprecated) [HAL daemon](https://freedesktop.org/wiki/Software/hal/) (lshal command).

There may be other packages besides HAL that do similar things. If you would like me to add support for one, I can.

**Comment by damarasekara** [comment]
Thanks for the reply. Appreciated, if you can add support for this.

**Comment by dbwiddis** [comment]
OSHI does support HAL already.

**Comment by dbwiddis** [comment]
```
sudo add-apt-repository ppa:mjblenner/ppa-hal
sudo apt-get update
sudo apt-get install hal
```

**Comment by damarasekara** [comment]
Thanks for this. I am trying to install HAL on Fedora but no success yet.

**Comment by dbwiddis** [comment]
I've looked all over for options and HAL is the only one that doesn't require root (because it runs as a daemon as root and provides the other access).  

Ultimately the information that most tools access is in either `/sys/class/dmi/id/product_name` or `/sys/class/dmi/id/board_serial`.  Both of these are read-only root files in sysfs.   It's possible to write a shell script which executes on boot to change their permissions, and I could let OSHI attempt to parse these.  If you can't get `hald` working I can work on this.

**Comment by damarasekara** [comment]
Thanks and appreciated if you can give me that solution then.

**Comment by dbwiddis** [comment]
Can you list which files in `/sys/class/dmi/id` have "serial" in their name? On my Ubuntu VM I have `product_serial`, `chassis_serial`, and `board_serial`.  Any others I should look for?

**Comment by damarasekara** [comment]
No. Those are fine. Thanks again.

**Comment by dbwiddis** [comment]
I'll have a snapshot up tomorrow sometime.

**Comment by dbwiddis** [comment]
I've added checking of the product_serial and board_serial files in #240 .  Snapshot is updated if you'd like to test it.     The chmod will need to be placed in a bootup script (run as root) to restore those permissions after each reboot.

**Comment by damarasekara** [comment]
Thanks a lot. It works.
