### ISSUE TITLE
Getting memory causes delay

### ISSUE THREAD

**Issue by Jazed** [dblock/oshi#246]
![](https://i.jazed.me/FHNpq.png)

**Comment by dbwiddis** [comment]
As mentioned in the chat, the first call to WMI anywhere in Oshi will incur a small delay, while subsequent calls are faster.   

However, there's no reason to require WMI for memory, since all the information is readily available in a single structure by calling [GlobalMemoryStatusEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366589(v=vs.85).aspx)

**Comment by dbwiddis** [comment]
So, after trying to implement this, I realize why I didn't use that the first time. :)

The [MEMORYSTATUSEX](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366770(v=vs.85).aspx) structure returned from [GlobalMemoryStatusEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366589(v=vs.85).aspx) returns the same total and very similar available values for total and available physical memory that we currently fetch from the [PERFORMANCE_INFORMATION ](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684824(v=vs.85).aspx) structure.

The docs for MEMORYSTATUSEX remind me why I didn't use it before. For ullTotalPageFile:

> The current committed memory limit for the system or the current process, whichever is smaller, in bytes. To get the system-wide committed memory limit, call GetPerformanceInfo.

Since we want the system-wide limit, that's what I did.  On my VM, this value is equal to the CommitLimit that we currently use (and which, per docs, is systemwide and thus better than the process limit).

The one statistic currently incurring the delay (if it is the first WMI call) is the "used swap" which is a tougher nut to crack.  My attempt to use `ullAvailPageFile` didn't match the existing WMI % used.  The docs for that read:

> The maximum amount of memory the current process can commit, in bytes. This value is equal to or smaller than the system-wide available commit value. To calculate the system-wide available commit value, call GetPerformanceInfo and subtract the value of CommitTotal from the value of CommitLimit.

But doing that gives a 0 available (100% used) result.

It is possible to retrieve the same percentage value currently used from the Performance Counters, rather than WMI; these ultimately access the same underlying information, and it's a question of whether to maintain the overhead of the multiple counters, or the single overhead of a WMI connection with its initial connection delay.

I'll continue to look into whether there is an alternative to WMI (other than a PerfMon counter) but I'm leaning toward leaving things as is, and possibly documenting the initial WMI setup/connection latency issue.

**Comment by Jazed** [comment]
I understand, thank you for your research and information.

**Comment by dbwiddis** [comment]
OK, after a few more hours of research I've concluded that the Perfmon counters are the only way to get the true "percent used" for swap.  The other values show percent/total committed, which isn't quite the same thing.   Options are adding/tracking the counters, or simply using the WMI query which reduces the overhead OSHI has to maintain for this (and other) counters.

WMI does incur a bit of a delay the first time it is called in OSHI (for any of the several stats it tracks -- processes, cpu ticks, swapfiles, disks, partitions, etc.), but following the setup, repeated calls should be much faster.  I've tested how long that lasts and it is at least 10 minutes.

The only other thing I think I could do is spawn a separate thread to try to initialize the WMI connection when first getting the SystemInfo object, but that may create more problems than it solves.   

I'll go ahead and close this issue as I think it's doing about the best it can.
