### ISSUE TITLE
OSX Uptime

### ISSUE THREAD

**Issue by Amjad121092** [dblock/oshi#247]
Hi,

The function systemInfo.getHardware().getProcessor().getSystemUptime() is really weird on OSX as it keeps jumping around as such.

Uptime: 17028 days, 10:01:22
Uptime: 17028 days, 10:01:23
Uptime: 3 days, 01:02:36
Uptime: 3 days, 01:02:37

**Comment by dbwiddis** [comment]
Are those four consecutive readings at 1 second apart?

Can you tell me what the result of command line `sysctl -n kern.boottime` is?

**Comment by dbwiddis** [comment]
OK, I've been able to reproduce this locally.  OSHI calculates up time by subtracting boot time (seconds since epoch) from the current time since the epoch.  But it appears that sometimes, the sysctl call for boot time returns 0, without giving any errors, and returning an up time in seconds since the epoch.

Since boot time doesn't change, there's no need to repeatedly call it, though. So i'll store the first successful value and that should solve this.

**Comment by dbwiddis** [comment]
Can you test the snapshot to see if your problem is fixed?
