### ISSUE TITLE
Release 1.3

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#63]
@hazendaz , please go through the process of releasing 1.3 and document the required steps and fixing any bugs or pom config settings along the way (I tried and failed.)

Please update [RELEASING.md](RELEASING.md) with the correct steps.  I have tried to do this on my own fork but may have some steps wrong: https://github.com/dbwiddis/oshi/blob/master/RELEASING.md

**Comment by hazendaz** [comment]
Here is what I did.  I don't have a lot of time right now due to work taking up my time.  Maybe you can translate this to the documentation.

mvn release:clean ~3 seconds
mvn release:prepare ~1 minute 36 seconds

This part asks for next version 1.3 so I just hit return to accept that and then it suggests    1.4-SNAPSHOT for next so I accept that too.  Then it asks for my gpg logon.

There are issues in the assembly so I'll fix those for next time around.  

mvn release:perform ~ 1 minute 27 seconds.

The release also pushes out GH Pages so it will now show 1.3 without snapshot.  However, that part didn't seem to work or maybe just hasn't caught up yet.  Everything did get pushed out to nexus.  I confirmed that.  And I'm pushing the release right now.

**Comment by hazendaz** [comment]
Site page caught up.  It shows 1.3 now.  Release is pushed to nexus.  Should be 2 to 3 hours before it shows up in the repos.  It didn't appear that it picked up the assembly so will need to look at that later.  It should have all the same as 1.2 once it shows up.

**Comment by dbwiddis** [comment]
Just submitted a PR documenting the below along with everything else I 
think I knew/know.

- I believe this eliminates the previous need for "mvn site", "mvn 
site:deploy", and "mvn clean install"
- Since we're not producing the zip file, it removes the need for "mvn 
package -p dist"
- It looks like the release process tagged the new release on github and 
uploaded some files, but it still required manual intervention to add 
release notes and publish the release (making it the current version), 
so I added that step.
