### ISSUE TITLE
How to get CPU serial number?

### ISSUE THREAD

**Issue by darielrll** [dblock/oshi#69]
I am doing a project in Java where I have to implement a license control, in addition to the possibility of implementing the project in trial mode. For this I need to take the fingerprint of the machine, may be the serial number of CPU, motherboard, hard disk, or MAC address. But it may happen that the machine has no network card or is defective or the hard disk is changed, so I want to prioritize more the serial number of the CPU and motherboard. How I can get the serial number of the CPU or the motherboard of the machine, besides considering it to be multiplatform, that is, that should work on Windows, Linux and Mac, I would be very grateful if you can send a sample code on how to do, thank you very much

**Comment by dbwiddis** [comment]
Oshi does not presently have this capability.  I am looking into adding it, but it looks problematic for several reasons:

* There's no way to get the info from Linux without root permissions (`dmidecode`) or external packages that the user is required to install.
* The only way to get it from Mac OS X is by parsing a command line `ioreg -l` (faster) or `system_profiler SPHardwareDataType` (slower, more info). 
* It is possible to get it programmatically from Windows, although the "easiest" way is by parsing a command line `wmic bios get serialnumber`.  

Additionally, using this information for licensing is problematic, due to people using virtual machines, being able to edit their registry, etc.

Given the large amount of work involved to get this working only on 2 platforms, and the unreliability of the information for practical use, I'm shying away from actually coding this up... if all you're doing is generating a license key, there are probably better (native code) ways to do it than using Java (perhaps scripts that allow sudo access).

My research has consistently pointed to the flaws of any hardware-based approach, and almost unanimously suggested using the "first MAC address" as a generally easy approach (built into Java already) that will work for most casual users, concluding the effort is not worth it for more complicated approaches.

If your project is low budget enough that you're looking to open source to get licence keys, you probably should be content with the MAC solution. If you've got expensive enough software that requires strong licensing, you might try to find a commercial solution.

**Comment by trejkaz** [comment]
I think a MAC address is really the only option that's fairly reliable and certainly the only option that's portable, but it's not without problems either.

The Java API for getting it, for instance, didn't work on Windows for some situations so we ended up using another method to get that. And even then, sometimes the first adapter is a mobile network device which appears and disappears depending on whether you're using it, so the "first" MAC address changes depending on that. If you could figure out which ones are those, you could exclude them, but I don't think it's possible to do that from Java's API.

On OSX we have a similar sort of phenomenon going on, where the network adapter supposedly (reported by users, might be laptops again because I don't see it happening here) completely disappears when the adapter is disabled.

**Comment by dbwiddis** [comment]
I suppose you could record all the MAC addresses and match any one of them... 

Looks like there are a few products out there that have already done the heavy lifting:
[TrueLicense](https://truelicense.java.net/index.html) looks rather capable.  They charge an annual fee for licensing but it seems to be a solid product.
[JLicense](http://www.websina.com/products/jlicense.html) is free for the binary or $50 for source code to implement a simpler licensing scheme (that probably doesn't protect as well against copying the license file to multiple machines).

Back to this particular ticket.  Wouldn't mind trying to write the code to return any of the values (if available) if it could truly be cross-platform.  But the root access required to get anything unique in Linux seems to be a showstopper.

**Comment by dbwiddis** [comment]
Looks like someone has written the necessary code to do this.  See the Hardware4*.java files on this project: https://github.com/sarxos/secure-tokens/tree/master/src/main/java/com/github/sarxos/securetoken/impl

I'll work on copying those files over and seeing what I can implement here.

**Comment by dbwiddis** [comment]
Well, I ended up using a lot less code from the secure-tokens project than I thought, but it did give me a few ideas, including the layered fallback (try root, then try non-root lshal if installed, then cpuid).  Linux still requires cooperation of the user, but that's an implementation issue, not a library issue.

Still don't think this is the best option for licensing, but the code's in.
