### ISSUE TITLE
ExceptionInInitializerError / NoClassDefFoundError in nt.CentralProcessor for unprivileged user 

### ISSUE THREAD

**Issue by mpdeimos** [dblock/oshi#86]
I'm running an application that uses oshi on a server with an unprivileged (non-admin) user. Whenever I want to access the processors of the server I'll get a NoClassDefFoundError that stems from an ExceptionInInitializerError in nt.CentralProcessor (OS is Win Server 2012, oshi 1.4).

After debugging I found that the static initializers throw several RuntimeExceptions which may yield to the above described problem, see e.g.  https://github.com/dblock/oshi/blob/52b5fbfd185517d1c5345ef1f624e11b073018a8/src/main/java/oshi/software/os/windows/nt/CentralProcessor.java#L127

The corresponding PDH error code is 0x800007D0 (PDH_CSTATUS_NO_MACHINE), see https://msdn.microsoft.com/en-us/library/windows/desktop/aa373046%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

According to  http://blog.bugrapostaci.com/tag/pdh_cstatus_no_machine/ it seems that my user does not have the required permissions to run the query.

For debugging purposes I have commented out throwing of LastErrorException which yields to no processer load information, but at least no crash of the JVM.

I'm willing to help with a bugfix, however I am not familar with general error handling in oshi. So we could suppress throwing of errors, but what values should be returned instead if one queries the load for a processor?

**Comment by dblock** [comment]
I think the initializer code should run on first query to fix this. If you cannot get the information you should get an exception, but obviously not see the process die.

**Comment by mpdeimos** [comment]
and the type of the exception should still be LastErrorException, so a runtime exception, right?

**Comment by dblock** [comment]
I think so.

**Comment by dbwiddis** [comment]
A few comments here:

First, I don't like the static initializers.  I put that in as a workaround to maintain the same API as previous versions, but I would like to totally redesign the structure to model multi-core processors using appropriate objects and without static variables/initializers.  If there is a solution to this problem which requires dumping the static stuff, this would be a reasonable excuse to bump to 2.0 and change the API.

Second, @dblock commented that the initializer code "should run on first query".  Unfortunately for this particular counter, the first query will yield no results.  The results from this particular counter aren't returned until the second (and subsequent) queries.  So it makes sense to have an automated query run when it's initialized so the first user query will generate results.

All that said, I'm not sure we have been consistent with the types of errors/exceptions thrown.  And certainly an initializer shouldn't kill the program, just fail to initialize and then return exceptions on user acess.

My proposed solution would be to set variables to appropriate values to indicate the initialization failure, and then test for those values when a user calls code, returning either the exception, or perhaps a documented incorrect value (like -1) to signal failure and prompt the user to handle the issue on their end.

**Comment by mpdeimos** [comment]
> Unfortunately for this particular counter, the first query will yield no results.

Suspected this. Maybe run initialization in the constructor?

> All that said, I'm not sure we have been consistent with the types of errors/exceptions thrown.

From what I saw, it's sadly a mixture across the classes and having them runtime exceptions makes it hard to guess what to catch w/o looking at the implementation. Just as hint if you consider API changes in 2.0 :wink: 
Without changing signature it may be better to return -1

**Comment by dbwiddis** [comment]
> Suspected this. Maybe run initialization in the constructor?

In 2.0, with a single constructor for the "System Processor" yes.   In 1.x, with each Processor object representing one of many possible cores, having static variables suited the cause.   Although perhaps we could make a separate system processor object, instantiate that using the singleton pattern, and provide access to it from the Processor object(s).  This is what you get having a non-professional coder writing code. :)

> From what I saw, it's sadly a mixture across the classes 

I think the common answer is supposed to be an OperationNotSupportedException.  I might spend some time trying to standardize this.

**Comment by dbwiddis** [comment]
My proposal for a "proper" fix:
1. Create a new SystemProcessor class designed to be used as a singleton, and move static code from Processor into that class.
2. When initializing SystemProcessor and CentralProcessor objects, instead of throwing the LastErrorExceptions, simply initialize a value as a flag for failure (e.g., negative)
3. Leave the exceptions in for subsequent access, but do a test for the "failed initilization" and either return -1 for ticks, etc. or throw an OperationNotSupportedException.  ( @dblock  can vote which.)

**Comment by dblock** [comment]
I still don't understand this "save exception for later" problem.without digging deeper, if something needs to run twice you can do it anytime no?

**Comment by dbwiddis** [comment]
It's not so much the "running twice" that's the issue, as opening the query to begin with.  The general sequence for the PDH tick counters is:

1. Open a query
2. Add tick counters
3. Query counters (first time returns 0)
4. Query counters repeatedly (returns ticks between queries)
5. Close the query

Only step 4 needs to be in the "getTicks" method.  It's possible to put step 3 in there and return 0 to the user the first time they call it, but this doesn't buy us anything, because the exceptions are still thrown on steps 1 or 2, which are only ever done once.  (So we may as well do step 3 with them.)

So the question is what to do with failed permissions on step 1 or 2 (or even 3).  The current behavior is to throw a LastErrorException (JNA library, extends RuntimeException).  This causes the entire instantiation of the CentralProcessor to fail, preventing access to any of its methods.

My proposal to "save for later" is to recognize a failure in steps 1 or 2 (or 3) and rather than throwing an exception, simply store an appropriate value (possibly a variable containing the LastError code) that indicates this failure.  Then all the other methods on the CentralProcessor object would still work for the user; they would simply be unable to call the "getTicks" method (it would either throw an exception or return an invalid value such as -1).

In theory, some other error could cause exceptions in step 4 at a later time and we should continue to throw these.

**Comment by dblock** [comment]
I think it's all fine, try some code ;)

**Comment by dbwiddis** [comment]
won't be able to get to this until the weekend, so if @mpdeimos wants to take a crack first, be my guest.

**Comment by dbwiddis** [comment]
Looking over the code again, the exceptions are in the individual processor objects anyway (I use a common query for all of them) so static is appropriate there.  And based on the report, the error is not in the opening of the query (step 1), but in the adding of processor tick counters (step 2).  (Not sure if the uptime counter has the same problem?)

I think a possible solution is to replace the "int ret = ..." tests for errors with int "lastError" variables storing the error code during initialization for each of the counters initialized.  Then test for lastError != 0 before accessing the pointers (steps 3,4) which normally would have been updated.  It looks like that update only changes static variables, so returning early from the update method will end up returning 0 for all the tick counters... a reasonable value to expect for an unprivileged user.

**Comment by dbwiddis** [comment]
PR #87 should fix this issue by simply failing siliently and returning 0 for PDH counter permissions issues.

**Comment by mpdeimos** [comment]
That was fast :+1: 

I'll give it a try on Monday, thanks.

**Comment by dbwiddis** [comment]
This should be good to test on the [1.5-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/dblock/oshi-core/1.5-SNAPSHOT/).  I've done some testing here, but I'll wait on your go ahead before pushing the 1.5 release.

**Comment by mpdeimos** [comment]
just tested the snapshot, looks good (in terms of no exception occurring anymore). Thanks.
